#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = waybar &
exec-once = ~/.local/bin/hyprland-per-window-layout
exec-once = mako


exec-once = swww-daemon
exec-once = swww img /home/pkgears/Imagenes/Wallpapers/Kath.png --transition-type grow --transition-pos 0.9,0.1 --transition-duration 1 --transition-fps 144

# Guardar texto e imágenes en el historial
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
