###################
### MY PROGRAMS ###
###################
source = ./apps.conf


#################
### AUTOSTART ###
#################
source = ./autostart.conf

####################
### LOOK AND FEEL ###
#####################
source = ./look.conf


###################
### KEYBINDINGS ###
###################
source = ./keybindings.conf