shell /home/linuxbrew/.linuxbrew/bin/zsh

background #24283b
foreground #c0caf5

cursor #7aa2f7
cursor_text_color #1a1b26
# Haz que el cursor parpadee para encontrarlo rápido
cursor_shape block
shell_integration  no-cursor

# 0.85 es un buen equilibrio entre estética y legibilidad
background_opacity 0.85

# Esto permite que Hyprland maneje el desenfoque detrás de la ventana
background_blur 1