# Primero cargamos la imagen en memoria (Preload)
preload = /home/pkgears/Imagenes/Kath.png

# Luego la aplicamos al monitor (o a todos si dejas el espacio vacío antes de la coma)
# Si tienes varios monitores, puedes repetir esta línea cambiando la ruta
#wallpaper = {
#	monitor = DP-1
#	path=  /home/pkgears/Imagenes/Kath.png
#	fit_mode = cover
#}

#wallpaper = {
#        monitor = HDMI-A-1 
#        path=  /home/pkgears/Imagenes/Kath.png
#        fit_mode = cover
#}

wallpaper = DP-1, /home/pkgears/Imagenes/Kath.png
wallpaper = HDMI-A-1 /home/pkgears/Imagenes/Kath.png

# Desactivar el texto de bienvenida (splash) para un look más limpio
splash = false

# Totalmente opcional: si quieres que la imagen se adapte mejor
# ipc = off
