general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para bloquear
    before_sleep_cmd = loginctl lock-session    # Bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Encender pantalla al despertar
}

listener {
    timeout = 600                               # 5 minutos
    on-timeout = loginctl lock-session          # Bloquear pantalla
}

listener {
    timeout = 330                               # 5.5 minutos
    on-timeout = hyprctl dispatch dpms off       # Apagar monitor
    on-resume = hyprctl dispatch dpms on         # Encender al volver
}
